### ISSUE TITLE
overflow in implicit constant conversion

### ISSUE THREAD

**Issue by PaSaSaP** [d03n3rfr1tz3/HC-SR04#3]
https://github.com/d03n3rfr1tz3/HC-SR04/blob/c306b349bbf3bdb74c366e3d825124f6afa9d7f3/src/HCSR04.h#L27

Compiler says:
```
/somewhere/HC-SR04/src/HCSR04.h: In member function 'void HCSR04Sensor::begin(byte, byte*, byte)':
/somewhere/HC-SR04/src/HCSR04.h:27:143: warning: overflow in implicit constant conversion [-Woverflow]
   void begin(byte triggerPin, byte* echoPins, byte echoCount) { begin(triggerPin, echoPins, echoCount, 100000, eUltraSonicUnlock_t::unlockSkip); }
```

100000 is greater than INT_MAX for arduino.

**Comment by d03n3rfr1tz3** [comment]
Thank you for letting me know. You are absolutely right, I forgot that. Should be fixed with the next version, as I switched to more concrete integer types.
